=== raduandritoiu/gitProjects/RaduA_gate_two/UI/src/assets/xml/ForeignPartMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.siemens.com/ForeignPartMap" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.siemens.com/ForeignPartMap">

    <xsd:complexType name="ForeignPart">
    	<xsd:sequence>
    		<xsd:element name="Replacement" type="ReplacementPart"
    			maxOccurs="unbounded" minOccurs="1">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="isObsolete" type="xsd:boolean" use="optional"></xsd:attribute>
    	<xsd:attribute name="partNumber" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="manufacturer" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ReplacementPart">
    	<xsd:attribute name="partNumber" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ListOfForeignParts">
    	<xsd:sequence>
    		<xsd:element name="ForeignPart" type="ForeignPart" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="PartMap" type="ListOfForeignParts"></xsd:element>
</xsd:schema>

=== raduandritoiu/gitProjects/RaduA_gate_two/UI/src/assets/xml/ForeignPartMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<PartMap xmlns="http://www.siemens.com/ForeignPartMap" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siemens.com/ForeignPartMap ForeignPartMapping.xsd ">
  <ForeignPart isObsolete="true" manufacturer="siemens" partNumber="xyz">
    <Replacement partNumber="abc"/>
  </ForeignPart>
  <ForeignPart manufacturer="honeywell" partNumber="789">
    <Replacement partNumber="123"/>
    <Replacement partNumber="456"/>
    <Replacement partNumber="987"/>
  </ForeignPart>
  <ForeignPart manufacturer="honeywell" partNumber="212">
    <Replacement partNumber="312"/>
    <Replacement partNumber="412"/>
    <Replacement partNumber="512"/>
  </ForeignPart>
  <ForeignPart manufacturer="belimo" partNumber="912">
    <Replacement partNumber="913"/>
    <Replacement partNumber="914"/>
    <Replacement partNumber="915"/>
  </ForeignPart>
</PartMap>
